try:
    print('hello,world')
except Exception as e:
    print(e)


try:
    print('hello,world')
except:
    print('except')


